sonar.projectKey=jramosalc_ucv-ate-si-laboratorio12
sonar.organization=jramosalc

sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12

sonar.sourceEncoding=UTF-8
